<a href="https://colab.research.google.com/github/Jigyass/Data-Privacy-and-Data-Security-Models/blob/main/Encryption/Homomorphic_Encryption/Homomorphic_Encryption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
pip install phe

In [19]:
#Import libraries
import numpy as np
from phe import paillier

In [20]:
#Question 1
#Task (a)
#Alice generates random nonnegative integer entries for A while Bob generates random nonnegative integer entries for B.

In [21]:
# Alice generates a 5x8 matrix
A = np.random.randint(low=0, high=100, size=(5, 8))
# Bob generates an 8x4 matrix
B = np.random.randint(low=0, high=100, size=(8, 4))
print("Matrix A (Alice):")
print(A)
print("\nMatrix B (Bob):")
print(B)

Matrix A (Alice):
[[ 9 49 53 77 77 17 98 13]
 [89 49 76 95 79 15 83  0]
 [87 56 53 16 29 68 11 92]
 [63 27 82 57 89 68 17 60]
 [ 8 40 63 83 41 30 89 25]]

Matrix B (Bob):
[[30 34  0 11]
 [36 37 11 10]
 [84 11 88 20]
 [84 70  7 59]
 [39 73 94 97]
 [53 89 52 55]
 [41  1 94 91]
 [24 64 46 39]]


In [22]:
#Task (b)

# Generate Paillier keypair this keypair is generated for Alice and will be used by Bob
public_key, private_key = paillier.generate_paillier_keypair()

In [24]:
# Assuming Bob has Alice's public key (public_key) and his matrix B

# Encrypting each element of matrix B
encrypted_B = np.array([[public_key.encrypt(int(b)) for b in row] for row in B])

print("Encrypted Matrix B:")
print(encrypted_B)

Encrypted Matrix B:
[[<phe.paillier.EncryptedNumber object at 0x7d036b8259c0>


In [31]:
# Perform the encrypted matrix multiplication
C = np.empty([5, 4], dtype=object)  # Initialize an empty matrix for the result

for i in range(5):  # Iterate over rows of A
    for j in range(4):  # Iterate over columns of encrypted_B
        sum = public_key.encrypt(0)  # Start with an encrypted 0
        for k in range(8):  # Iterate over the elements in the row/column pair
            # Convert A[i][k] to a standard Python integer and then perform scalar multiplication
            product = encrypted_B[k][j] * int(A[i][k])  # Scalar multiplication
            sum = sum + product  # Homomorphic addition
        C[i][j] = sum

# C now contains the encrypted result of A x B



In [34]:
# Decrypting the result matrix C
decrypted_C = np.zeros([5, 4])  # Initialize an empty matrix for the decrypted result

for i in range(5):
    for j in range(4):
        decrypted_C[i][j] = private_key.decrypt(C[i][j])

print("Decrypted Matrix (Product of A and B):")
print(decrypted_C)
# Performing normal matrix multiplication of A and B
normal_product = np.dot(A, B)
print("Multiplication Values without Encryption")
print(normal_product)

Decrypted Matrix (Product of A and B):
[[21188. 16156. 23674. 24021.]
 [26077. 19510. 23900. 24635.]
 [17816. 20801. 16920. 14663.]
 [23750. 24439. 24172. 22226.]
 [21382. 15607. 21495. 21346.]]
Multiplication Values without Encryption
[[21188 16156 23674 24021]
 [26077 19510 23900 24635]
 [17816 20801 16920 14663]
 [23750 24439 24172 22226]
 [21382 15607 21495 21346]]
